sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Yts3Si/+wy3I5oezPEPMJY40rY6VipH19hsYLS01PBzUbljqGHyeYysC4STbWllal9KzMMs69RDtcehevFtbbzRZ1HvrhR/YgL8WwFbIy2VjkXwjlpjbEZMFekZLHMyGpiT1mePUbCBgb9lZRc8uGFjPgOjUxKHgYbUe4VjQc9Rb8/R2etNru7+Y3rmiZ8vib4Nrze/o7biHiIte4AWeF+0ns0iLHRZaDi05Wmr0V3fMynLSyk4MR32fPlnDQBg8sUY3xPJgzBtmK4Xzj23A0A6S7ZGBYEovE20g88wlANzLbGZ2AaVrchaLHBIwSOTVQODU0htuaiblZKFI2mGTp8bJz3GskFSdbzSgVYAsY6hoOJdMl0xCfPr8ki48JGyL53zDDntH+0edY4Uw2JvAc3ZligleJ/iWIiywnfi0i2G4d8err4360aJpovNfAYQIZiXtLvSOsVfIRFYM/WjuPStEvQnfv3blWybe7vT/zeQEyst/+Y128dIiY9FPLNhqWNO36ycJXrV95w6NuTYwisT/sCg2pHG2vtGptyzleG3+ud1AUED3KocdqS3YMawne0+KhF1Vdrs+vxFBxENLXiTEP79g07UcFuuYR/sg//OSlGnKL691HrS9Twol/V5A3WvWzb51xdrreqewSuQhFyrD4VnLGz8WLJATSc4BCtY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Mr.-Honey-s-Large-Business-Dictionary--German-English-_3220
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy